#!/bin/bash

echo "═══════════════════════════════════════════════════════════════════════"
echo "R2D2 HARDWARE DIAGNOSTIC CHECKLIST"
echo "═══════════════════════════════════════════════════════════════════════"
echo ""
echo "SOFTWARE IS WORKING! Audio mixer is configured correctly."
echo "The problem is in the HARDWARE or WIRING."
echo ""

echo "STEP 1: Verify PAM8403 Power Supply"
echo "───────────────────────────────────────────────────────────────────────"
echo "Use a multimeter to check:"
echo ""
echo "  A) Jetson Pin 2 (5V supply):"
echo "     $ Attach multimeter RED to Jetson Pin 2 (J30 Pin 2)"
echo "     $ Attach multimeter BLACK to Jetson Pin 6 (GND)"
echo "     SHOULD READ: ~5V (4.7V - 5.3V is OK)"
echo ""
echo "  B) PAM8403 +5V pin:"
echo "     $ Attach multimeter RED to PAM8403 +5V pin"
echo "     $ Attach multimeter BLACK to PAM8403 GND"
echo "     SHOULD READ: ~5V (4.7V - 5.3V is OK)"
echo ""
echo "  If NOT reading 5V on PAM8403:"
echo "    → Power wire may be loose or disconnected"
echo "    → Check solder connections on both ends"
echo "    → Try reseating wires in breadboard or connectors"
echo ""

echo "STEP 2: Verify Audio Signal Path (Wiring)"
echo "───────────────────────────────────────────────────────────────────────"
echo "Carefully check each connection:"
echo ""
echo "  1. Jetson J511 Pin 9 (HPO_L) → PAM8403 LIN"
echo "     ✓ Wire secure in breadboard/connector?"
echo "     ✓ No solder bridges?"
echo "     ✓ Correct pin?"
echo ""
echo "  2. Jetson J511 Pin 2 (AGND) → PAM8403 GND (audio)"
echo "     ✓ Wire secure?"
echo "     ✓ Is this a DIFFERENT connection than power GND?"
echo ""
echo "  3. Jetson J30 Pin 6 (GND) → PAM8403 GND (power)"
echo "     ✓ Wire secure?"
echo "     ✓ Connected to SAME GND point as audio GND?"
echo ""
echo "  4. PAM8403 L+ → Speaker +"
echo "     ✓ Red wire connected?"
echo "     ✓ Solder joint solid?"
echo ""
echo "  5. PAM8403 L− → Speaker −"
echo "     ✓ Black wire connected?"
echo "     ✓ Solder joint solid?"
echo ""

echo "STEP 3: Verify Speaker is Working"
echo "───────────────────────────────────────────────────────────────────────"
echo "Test the speaker independently:"
echo ""
echo "  Option A: Battery test (safest)"
echo "    1. Take a 1.5V AA battery"
echo "    2. Touch positive (red) terminal to speaker +"
echo "    3. Touch negative (black) terminal to speaker −"
echo "    4. You should hear a CLICK"
echo "    → If no click: speaker is defective, try different speaker"
echo ""
echo "  Option B: Direct PAM8403 test (if you have another power supply)"
echo "    1. Verify PAM8403 has 5V power (from Step 1)"
echo "    2. Short circuit input (LIN to GND) momentarily"
echo "    3. You should hear a CLICK or POP from speaker"
echo "    → If no sound: speaker connection problem"
echo ""

echo "STEP 4: Verify Jetson is Sending Audio Signal"
echo "───────────────────────────────────────────────────────────────────────"
echo "Check if J511 Pin 9 (HPO_L) has an audio signal:"
echo ""
echo "  With a multimeter or oscilloscope:"
echo "    1. Set multimeter to AC voltage (NOT DC)"
echo "    2. Place probe on Jetson J511 Pin 9 (HPO_L)"
echo "    3. Place ground probe on Jetson J511 Pin 2 (AGND)"
echo "    4. Run: speaker-test -t sine -f 1000 -c 2 -D hw:1,0 -d 3"
echo "    5. Multimeter SHOULD show a voltage fluctuation (AC signal)"
echo "       Even 50-500mV AC is valid"
echo ""
echo "    If NO signal detected:"
echo "      → Issue is in Jetson software/firmware (unlikely - mixer was ON)"
echo "      → Try restarting Jetson"
echo ""
echo "    If signal IS detected:"
echo "      → Problem is in PAM8403 amplifier or speaker connection"
echo ""

echo "═══════════════════════════════════════════════════════════════════════"
echo "MOST LIKELY PROBLEMS (in order of probability):"
echo "═══════════════════════════════════════════════════════════════════════"
echo ""
echo "  1. ⚠ PAM8403 has NO POWER (5V not reaching it)"
echo "       → Check with multimeter (Step 1)"
echo ""
echo "  2. ⚠ Loose wiring connections (breadboard/solder)"
echo "       → Check each wire physically (Step 2)"
echo ""
echo "  3. ⚠ Speaker connection reversed (+ and − swapped)"
echo "       → Speakers only produce sound in one polarity direction"
echo "       → Try swapping speaker wires if amp has power"
echo ""
echo "  4. ⚠ Defective speaker"
echo "       → Test with battery (Step 3 Option A)"
echo ""
echo "  5. ⚠ PAM8403 amplifier module is defective"
echo "       → Less common, but possible"
echo ""

echo "═══════════════════════════════════════════════════════════════════════"
echo "NEXT STEPS:"
echo "═══════════════════════════════════════════════════════════════════════"
echo ""
echo "1. Perform multimeter test on PAM8403 +5V pin (STEP 1)"
echo "2. If you see 5V: Problem is wiring or speaker (check STEP 2)"
echo "3. If you see 0V: Check power wire connection from Jetson Pin 2"
echo "4. Once power is confirmed, test speaker independently (STEP 3)"
echo ""
echo "Report back with:"
echo "  - Voltage reading at PAM8403 +5V pin"
echo "  - Whether speaker clicked when tested with battery (if applicable)"
echo "  - Any visible loose wires or bad solder joints"
echo ""
echo "═══════════════════════════════════════════════════════════════════════"
