#!/bin/bash
# R2D2 Face Recognition & Audio Notification Test Procedure
# This script guides you through testing the system

echo ""
echo "╔══════════════════════════════════════════════════════════════════╗"
echo "║                                                                  ║"
echo "║  🤖 R2D2 FACE RECOGNITION & AUDIO NOTIFICATION TEST PROCEDURE   ║"
echo "║                                                                  ║"
echo "╚══════════════════════════════════════════════════════════════════╝"
echo ""
echo "This test will verify that your R2D2 recognizes your face and beeps."
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📋 TEST SETUP"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "You'll need THREE TERMINALS:"
echo ""
echo "Terminal 1: Face Recognition Pipeline"
echo "  → Camera & face detection"
echo "  → Run: cd ~/dev/r2d2/ros2_ws && source install/setup.bash"
echo "         ros2 launch r2d2_bringup r2d2_camera_perception.launch.py enable_face_recognition:=true"
echo ""
echo "Terminal 2: Audio Notification Service (already running)"
echo "  → Status: sudo systemctl status r2d2-audio-notification.service"
echo "  → Logs: sudo journalctl -u r2d2-audio-notification.service -f"
echo ""
echo "Terminal 3: Real-time Monitor (THIS TERMINAL)"
echo "  → Run: python3 ~/dev/r2d2/monitor_face_recognition.py"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🎬 TEST PROCEDURE"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Step 1: Start Terminal 1 - Face Recognition Pipeline"
echo "        Wait for it to initialize (30 seconds)"
echo ""
echo "Step 2: In THIS terminal, start the monitor:"
echo "        python3 ~/dev/r2d2/monitor_face_recognition.py"
echo ""
echo "Step 3: Run through the test scenarios:"
echo ""
echo "  TEST A: Face Recognition"
echo "    ├─ Position yourself in front of camera"
echo "    ├─ You should see: '✅ severin' in the monitor"
echo "    └─ You should HEAR: 🔊 Single beep (400 Hz, 0.5 sec)"
echo ""
echo "  TEST B: No Face (Unknown)"
echo "    ├─ Turn away from camera or cover it"
echo "    ├─ You should see: '❓ unknown' in the monitor"
echo "    └─ No beep (expected behavior)"
echo ""
echo "  TEST C: Loss Alert"
echo "    ├─ Start with face recognized (TEST A)"
echo "    ├─ Turn away for 5+ seconds"
echo "    ├─ Wait for confirmation..."
echo "    ├─ You should HEAR: 🔔🔔 Double beep (loss alert)"
echo "    └─ Monitor should show transition to '❓ unknown'"
echo ""
echo "  TEST D: Recovery"
echo "    ├─ Show your face again after loss alert"
echo "    ├─ You should see: '✅ severin' in monitor"
echo "    └─ You should HEAR: 🔊 Single beep (welcome back!)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📊 EXPECTED OUTPUT IN MONITOR"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Real-time status line (updates every frame):"
echo "  10:14:45.234 | Face Recognition: ✅ severin"
echo ""
echo "Audio events (appear on new line when triggered):"
echo "  10:14:47.892 | 🔊 Audio Event: 🎉 Recognized severin!"
echo "  10:14:53.456 | 🔊 Audio Event: ❌ severin lost (confirmed)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🎯 QUICK START"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Run this NOW to start the monitor:"
echo ""
echo "  python3 ~/dev/r2d2/monitor_face_recognition.py"
echo ""
echo "Then in another terminal, start face recognition:"
echo ""
echo "  cd ~/dev/r2d2/ros2_ws && source install/setup.bash"
echo "  ros2 launch r2d2_bringup r2d2_camera_perception.launch.py enable_face_recognition:=true"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
